config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: { locale: 'en'} do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Ckeditor::Engine => '/ckeditor'
    resources :articles, only: [:show, :index]
    root :to => "articles#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# Article model, each article has set of translations
class Article < ApplicationRecord
  # Attrs we want to translate
  translates :question, :answer, touch: true
  # Validates article question and answer to be present and unique
  validates :question, :answer, presence: true, uniqueness: true
  # Each article has nested attributes for translations
  accepts_nested_attributes_for :translations, allow_destroy: true
  # Used for pagination, number of articles per page.
  self.per_page = 10
  # Used for easy and better access of translation attributes
  globalize_accessors
  # A scope to get recent articles
  scope :recent, -> {order(updated_at: :desc)}
  # A scope to include translations for N + 1 query issues
  scope :include_translations, -> {includes(:translations)}

  # Return recent articles in a specific page.
  def self.recent_articles(page_no = 1)
    Article.include_translations.recent.paginate(page: page_no)
  end

  # Used since we would observe the english translation itself which has the content of our attributes
  class Translation
    # Checks if our data changed
    def changed?
      (self.saved_change_to_question? || self.saved_change_to_answer?)
    end
    # checks if our source translation article is english.
    def is_english?
      self.locale.to_s == 'en'
    end
  end
end

app/models/article_observer.rb
# Observer to catch events/callbacks of Article, used for single responsibility and efficient testing.
class ArticleObserver < ActiveRecord::Observer
  observe Article::Translation

  def after_save(article_translation)
    # Only translate articles that are english and changed.
    if article_translation.is_english? && article_translation.changed?
      # No need to use a sidekiq worker, since Aws is highly available and we want to save on live data
      # The traffic is much higher in the user level than the admin level
      # This is a service to translate the article
      article_service = ArticleService.new(article_translation, 'en', 'de')
      article_service.translate
    end
  end
end

app/models/article_repository.rb
# Following DDD, Article repository is used to set and get our article since it has interaction with our translations
class ArticleRepository
  # Initializing our article
  def initialize(article)
    @article = article
  end
  # Saving our translated article into our database.
  def save_translated(attrs, lang)
    puts "Attrs are: #{attrs}"
    # Getting/Creating the article at which we are going to save our translated attributes in
    lang_article = @article.translations.with_locale(lang.to_sym).first_or_create!
    # Save our attributes
    attrs.each do |key, value|
      lang_article[key] = value
    end
    # Save our translated article.
    lang_article.save!
    lang_article
  end
end

app/models/article_service.rb
# Article Service class
class ArticleService
  # Used to translate our article given:
  # - Our Article
  # - Our source language
  # - Our target language

  def initialize(article_translation, source_lang, target_lang)
    @article_translation = article_translation
    @source_lang = source_lang
    @target_lang = target_lang
    # TODO: now article_translation.article not implemented in globalize gem, 
    # adding belongs_to caused other issues to wrong validation which does not allow to save the article.
    @article = Article.find(@article_translation.article_id)
  end
  def translate
    aws_translate_service = Aws::TranslateService.new
    translated_question = aws_translate_service.translate(@article_translation.question, @source_lang, @target_lang)
    translated_answer = aws_translate_service.translate(@article_translation.answer, @source_lang, @target_lang)
    translated_article_attrs = {question: translated_question, answer: translated_answer}
    article_repo = ArticleRepository.new(@article)
    article_repo.save_translated(translated_article_attrs, @target_lang)
  end
end

app/models/ckeditor/asset.rb
# Auto generated by Ckeditor for the ability to save images
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# Auto generated by Ckeditor for the ability to save images
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# Auto generated by Ckeditor for the ability to save images
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale =  params[:locale] || I18n.default_locale
  end
end

app/controllers/articles_controller.rb
# Our Main Articles Controller used to list and show articles.
class ArticlesController < ApplicationController
  # GET /articles/:id
  # This action is used to return a specific article
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles
  def index
    # Returning recent articles paginated
    @articles = Article.recent_articles(params[:page])
  end
end

app/controllers/rails_admin_locale_controller.rb
class RailsAdminLocaleController < ActionController::Base
  before_action :set_locale
 
  def set_locale
    I18n.locale = :en
  end
   
  protect_from_forgery with: :exception

end

app/helpers/application_helper.rb
module ApplicationHelper
  def datetime_ago(datetime)
    begin
      timeago_tag datetime, :nojs => true, :lang => I18n.locale
    rescue
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_truncate(value, number=100)
    value.truncate(number)
  end
end

app/views/articles/_article.html.haml
.post{data: {article_id: article.id}}
  .time
    %span
      = t('updated')
    = datetime_ago(article.updated_at)
  %br
  .question
    = raw article.question
  %hr
  .answer
    %p
      = raw article_truncate(article.answer)
  .continue-reading
    = link_to t('read_more'), article_path(article, locale: I18n.locale), class: 'btn btn-primary'

app/views/articles/index.html.haml
%h1
  = t('articles')
- cache([@articles, locale: I18n.locale]) do
  #all
    #content
      .container
        .col-sm-12.article-listing
          - @articles.each do |article|
            - cache([article, locale: I18n.locale]) do
              = render article
        = will_paginate @articles

app/views/articles/show.html.haml
- cache([@article, locale: I18n.locale]) do
  .container
    .row
      .col-xs-12
        .card.mb-4
          .card-body
            .card-time
              %span
                = t('updated')
              = datetime_ago(@article.updated_at)
            // Article Question
            .card-title.card-question#card-question
              = raw @article.question
            %hr
            // Article Answer
            .card-text.card-answer#card-answer
              = raw @article.answer

app/views/layouts/_header.html.haml
// Header HTML
.navbar.navbar-translator
  .navbar-header
    .navbar-buttons
      %button.navbar-toggle.navbar-light{type: 'button', "data-toggle" => 'collapse', "data-target" => "#navbar_content"}
        %span.sr-only
          Toggle navigation
        %i.fa.fa-align-justify
  .collapse.navbar-collapse#navbar_content
    %ul.nav.navbar-nav.navbar-left
      %li.nav-item.active
        = link_to root_path(locale: I18n.locale), class: 'nav-link' do
          %span.sr-only
            (current)
          = t('articles')

    %ul.nav.navbar-nav.navbar-right
      %li.nav-item.dropdown
        %a.dropdown-toggle.btn{"data-toggle": "dropdown"}
          = t(I18n.locale)
          %span.caret
        %ul.dropdown-menu.navbar-translator
          - I18n.available_locales.each do |lang|
            %li
              = link_to t(lang), root_path(locale: lang)

app/views/layouts/application.html.haml
%html
  %head
    %title Translator
    %meta{content: "user-scalable=yes, initial-scale=1, maximum-scale=8, user-scalable=yes, minimum-scale=0.5, width=device-width, height=device-height", name: "viewport" }/
    %meta{charset: "utf-8"}
    %meta{name: 'robots', content: 'all,follow'}
    %meta{name: 'googlebot', content: ''}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{name: 'description', content: ''}
    %meta{name: 'keywords', content: ''}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
    = csp_meta_tag
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'